### ISSUE TITLE
!rs serve

### ISSUE THREAD

**Issue by hadilou** [Element84/robosat-jupyter-notebook#5]
Hi, Thank you for the great work.
I followed the steps mentioned in the notebook and  using rs serve as a debugging tool. However while satellites tiles do show up, segmentation masks do not appear. Below is the command I used. I try to figure this out by analyzing the serve.py file but still. Any help or tip is welcome.

`!export MAPBOX_ACCESS_TOKEN=MyToken \

./rs serve --model /app/config/model-unet-.toml --dataset /app/config/dataset-building.toml --checkpoint /app/container_mount/checkpoints/checkpoint-00066-of-00100.pth --tile_size 256 --host 0.0.0.0 --url https://api.mapbox.com/v4/mapbox.satellite/18/39.92890/32.82483@2x.webp?access_token=MyToken

`

**Comment by stark525** [comment]
Hi, thanks! Here are a couple things to try:
1) `--model /app/config/model-unet-.toml` is this correct file path for your model?
2) Is your zoom level in your map different than the zoom your model is trained on? You may have to either adjust the default zoom level for when the app launches or manually change the zoom
3) Try changing the default AoI to where you trained your data if it's not already using that. See this: 

The sources for both 2) and 3) are shown here: https://github.com/Element84/robosat/commit/984f0e27465c6fd335c30a71d477162a7196526a#diff-acf2a7a1861e4105aaed8d68f96ad270

Let me know how it goes!

**Comment by hadilou** [comment]
Hi. thanks for your comment. I have already performed the steps you mentioned. But nothing has changed.
1.) the model and dataset paths are correct
2.) My zoom levels are the same, I also tried z+1, z-1 etc manually
3.) The default location has been changed to where I trained my model

Despite performing these changes, I still have no segmentation masks

**Comment by stark525** [comment]
Hmm, this step gave us some problems initially, I'm sorry that it is not working.

Are there any docker logs or browser console logs that might any additional info?

We're going to try to spin up our instance and remember what we did to troubleshoot and will get back to you soon!
